#!/usr/bin/env bash

source "$(dirname "$(readlink -f "$BASH_SOURCE")")"/vendor/minond/debug/debug

SERVIES_FILE_CONN=
SERVIES_FILE_STATUSES=
SERVIES_FILE_HEADERS=

SERVIES_ROUTE_EXTRACTOR=()
SERVIES_ROUTE_GROUPS=()
SERVIES_ROUTE_HANDLERS=()
SERVIES_ROUTE_METHODS=()
SERVIES_ROUTE_PATTERN=()
SERVIES_ROUTE_URLS=()

declare -A SERVIES_HTTP_STATUS_CODES=(
    ["200"]="OK"
    ["404"]="Not Found"
    ["500"]="Internal Server Error"
)

DEBUG_ROUTER_COLOR="$RANDOM"

#=== FUNCTION =================================================================
#        NAME: servies:pipe
# DESCRIPTION: create a fifo that acts as a pipe from a program to another
# PARAMETER 1: name of fifo file
# PARAMETER 2: name of statuses file
# PARAMETER 3: name of headers file
#==============================================================================
servies:pipe() {
    SERVIES_FILE_CONN=$1
    SERVIES_FILE_STATUSES=$2
    SERVIES_FILE_HEADERS=$3

    mkfifo "$SERVIES_FILE_CONN" && touch "$SERVIES_FILE_STATUSES" "$SERVIES_FILE_HEADERS"

    # if we were able to create the fifo, this makes sure to remove it when
    # this program ends
    if [ $? -eq 0 ]; then
        # shellcheck disable=SC2064
        # ignoring shellcheck's single quotes on trap calls rule because I do
        # want the variable to be expanded upon call time
        # https://github.com/koalaman/shellcheck/wiki/SC2064
        trap "rm -f '$SERVIES_FILE_CONN' '$SERVIES_FILE_STATUSES' '$SERVIES_FILE_HEADERS'" EXIT
    fi
}

#=== FUNCTION =================================================================
#        NAME: servies:listen
# DESCRIPTION: makes netcat listen for a request
# PARAMETER 1: listen on this host
# PARAMETER 2: listen on this port
#==============================================================================
servies:listen() {
    local host=$1
    local port=$2

    debug server "listening for requests on $HOST:$PORT"

    while true; do
        cat < "$SERVIES_FILE_CONN" | nc -l "$host" "$port" > >({ servies:handle; cat >/dev/null; })

        # resetting timer because handler is in a subshell
        debug:time_reset
    done
}

#=== FUNCTION =================================================================
#        NAME: servies:handle
# DESCRIPTION: reads a request form netcat and sends back a response
# PARAMETER 1: name of fifo file
# PARAMETER 2: listen on this host
# PARAMETER 3: listen on this port
#==============================================================================
servies:handle() {
    local method=
    local url=

    # requests look like this:
    # GET /hi/marcos HTTP/1.1
    # Host: localhost:8080
    # Connection: keep-alive
    # Accept: text/html
    # User-Agent: Mozilla/5.0
    # Accept-Encoding: gzip, deflate, sdch
    # Accept-Language: en-US,en;q=0.8
    while read line; do
        line=$(echo "$line" | tr -d '\r\n')

        # if this is the first line, save the route information
        # all we really need for basic routing is the informaiton
        # that is included in the first line of the request:
        # GET /hi/marcos HTTP/1.1
        # so if this is the first time parsing the request, save that
        # first line
        if [ -z "$url" ]; then
            url=$(echo "$line" | sed -n 's/.* \(\/.*\) .*/\1/p')
            method=$(echo "$line" | sed -n 's/\(.*\) .* .*/\1/p');
        fi

        # if the trimmed line is empty, we have parsed all the headers
        # and are moving into the body of the request. now we can start
        # working on the reponse.
        if [ -z "$line" ]; then
            # do not care what the body includes, so we will stop reading the
            # request after routing it. if we wanted to add body parsing, it
            # would go here.
            servies:route "$method" "$url"
            break
        fi
    done
}

#=== FUNCTION =================================================================
#        NAME: servies:route
# DESCRIPTION: find a request handler and call the action
# PARAMETER 1: http method
# PARAMETER 2: url
#==============================================================================
servies:route() {
    local action=
    local values=
    local groups=

    local method=$1
    local url=$2

    for ((i=0;i<${#SERVIES_ROUTE_METHODS[@]};i++)) do
        # go throught ever single saved route until we find one that has a
        # pattern that matches the requested url
        servies:route_matches_index "$i" "$method" "$url"
        if [ $? -eq 0 ]; then
            # use the extractor string with sed to get all of the url group
            # values
            values=$(echo "$url" | sed -E "${SERVIES_ROUTE_EXTRACTOR[$i]}")
            groups="${SERVIES_ROUTE_GROUPS[$i]}"

            # cast to array. better way to do this??
            groups=( $groups )
            values=( $values )

            # save the action we will be calling later and stop here. handlers
            # are always processed in sequential order, and which ever one is
            # set, and therefore found, first takes precedence
            action="${SERVIES_ROUTE_HANDLERS[$i]}"
            break
        fi
    done

    # now using the list of groups in the url and their values extracted, we
    # declare them in the local scope. perhaps there's a way to do this so
    # the newly declared variables don't muck up this function's scope.
    for i in $(seq 0 "$(echo "${groups[*]}" | wc -w)"); do
        # prefixing variables here because we evaluate the action in the same
        # scope and don't want name conflicts.
        local servies_group="${groups[$i]}"
        local servies_value="${values[$i]}"

        # if for some odd reason we have an empty variable name (group, here)
        # skip over it. empty values are fine
        [ -z "$servies_group" ] && continue

        # TODO perhaps a sub-shell?
        declare "$servies_group"="$servies_value"
    done

    # if we couldn't find a matching route, we won't have a handler. if this
    # the case the we default to the `not_found` action, which can be
    # overwritten by the user
    [ -z "$action" ] && action=not_found

    # hard-setting color because handler is in a subshell
    debug:set_color router "$DEBUG_ROUTER_COLOR"
    debug router "routing $method $url to $action"

    servies:reset_response

    stdout=$(mktemp)
    stderr=$(mktemp)

    # TODO look into using a sub-shell instead of using eval
    # send errors to error log??
    eval "$action" >"$stdout" 2>"$stderr"
    servies:send_response $? "$(cat $stdout)" "$(cat $stderr)"
}

#=== FUNCTION =================================================================
#        NAME: servies:reset_response
# DESCRIPTION: reset variables used to store/track response info
#==============================================================================
servies:reset_response() {
    status 200
    echo "" > "$SERVIES_FILE_HEADERS"
}

#=== FUNCTION =================================================================
#        NAME: servies:send_response
# DESCRIPTION: dump a response string into the connection fifo
# PARAMETER 1: handler's exit code
# PARAMETER 2: anything you want to send back to a client
# PARAMETER 3: error output, send back in case of an error
#==============================================================================
servies:send_response() {
    local exit_code="$1"
    local content=
    local response=

    if [ "$exit_code" -eq 0 ]; then
        content="$2"
    else
        status 500
        content="$3"
    fi

    header "Content-Length" "${#content}"

    # builds a resopnse string that looks like this:
    # HTTP/1.1 200 OK
    # Content-Type: text/plain
    # Content-Length: 484
    # [a blank line]
    # response body
    response=$response$(cat "$SERVIES_FILE_STATUSES")
    response=$response$(cat "$SERVIES_FILE_HEADERS")
    response=$response$(echo -e "\n\n$content")

    echo "$response" > "$SERVIES_FILE_CONN"
}


#=== FUNCTION =================================================================
#        NAME: servies:route_matches_index
# DESCRIPTION: given a url and a request method, and also the index of the
#              routes array of the route in question, this will check if
#              the route in question can be used to handle the request
# PARAMETER 1: index of the routes array to check
# PARAMETER 2: request method
# PARAMETER 3: url
#==============================================================================
servies:route_matches_index() {
    local i="$1"
    local method="$2"
    local url="$3"

    # first check the methods match, that's an easy comparison.
    if [ "${SERVIES_ROUTE_METHODS[$i]}" = "$method" ]; then
        # them we check if the request's url matches the url pattern we
        # generated for this route
        echo "$url" | grep -e "${SERVIES_ROUTE_PATTERN[$i]}" &> /dev/null
    else
        # method doesn't match. don't bother with url comparison
        false
    fi
}

#=== FUNCTION =================================================================
#        NAME: go
# DESCRIPTION: start a server
#==============================================================================
servies:start() {
    [ -z "$PORT" ] && PORT=8080
    [ -z "$HOST" ] && HOST=0.0.0.0

    servies:pipe "$(mktemp -u)" "$(mktemp -u)" "$(mktemp -u)"
    servies:listen "$HOST" "$PORT"
}

#=== FUNCTION =================================================================
#        NAME: servies:url_pattern
# DESCRIPTION: converts a human-friendly url into a string you can use as a
#              match expression
# PARAMETER 1: the url you want to convert into an expression
#==============================================================================
servies:url_pattern() {
    local pattern=$(echo "$1" | \
        # make slashes optional: /welcome/ => \/?welcome\/?
        sed 's/\//\/?/g' | \
        # replace human groups with regex groups: /welcome/:name => /welcome/.\+
        sed -E 's/:(\w*)/.\\+/g' | \
        # replace question makes with optional group match expressions:
        # /welcome/:name => /welcome/\w\+\?
        sed 's/?/\\?/g')

    echo "^${pattern}\$"
}

#=== FUNCTION =================================================================
#        NAME: servies:url_extractor
# DESCRIPTION: converts a human-friendly url into a sed match and replace
#              expression that can be used to extract match values
# PARAMETER 1: the url you want to convert into an expression
#==============================================================================
servies:url_extractor() {
    local url="$1"
    local groups=$(servies:url_groups "$url" | wc -w)

    local replace=
    local search=$(echo "$url" | \
        # escape forward slashes
        sed 's/\//\\\//g' | \
        # optional forward slashes
        sed 's/\//\/{0,}/g' | \
        # replace groups with work matching expression
        sed -E 's/:(\w*)/(\\w\+)/g' | \
        # replace question marks with regex expression for optional matches
        sed 's/?/{0,}/g')

    if [ "$groups" -ne 0 ]; then
        for i in $(seq 1 "$groups"); do
            replace="$replace \\$i"
        done
    fi

    echo "s/$search/$replace/"
}

#=== FUNCTION =================================================================
#        NAME: servies:url_groups
# DESCRIPTION: searches a url for groups (:group_name)
# PARAMETER 1: the url you want to get groups from
#==============================================================================
servies:url_groups() {
    (echo "$1" | \
        grep -o -e ':\w\+' | \
        grep -o -e '\w\+') | xargs
}

#=== FUNCTION =================================================================
#        NAME: servies:save_route
# DESCRIPTION: add a new route
# PARAMETER 1: method
# PARAMETER 2: url string (include first forward slash)
# PARAMETER 3: command name
#==============================================================================
servies:save_route() {
    local method=$1
    local url=$2

    shift
    shift
    local handler="$*"

    SERVIES_ROUTE_PATTERN+=("$(servies:url_pattern "$url")")
    SERVIES_ROUTE_EXTRACTOR+=("$(servies:url_extractor "$url")")
    SERVIES_ROUTE_GROUPS+=("$(servies:url_groups "$url")")
    SERVIES_ROUTE_URLS+=("$url")
    SERVIES_ROUTE_METHODS+=("$method")
    SERVIES_ROUTE_HANDLERS+=("$handler")

    debug route "creating route: $method $url"
}

#=== FUNCTION =================================================================
#        NAME: status
# DESCRIPTION: output a header
# PARAMETER 1: header name
# PARAMETER 2: header value
#==============================================================================
status() {
    local code=$1
    local name=$2

    [ -z "$name" ] && name="${SERVIES_HTTP_STATUS_CODES[$code]}"

    echo HTTP/1.1 "$code" "$name" > "$SERVIES_FILE_STATUSES"
}

#=== FUNCTION =================================================================
#        NAME: header
# DESCRIPTION: output a header
# PARAMETER 1: header name
# PARAMETER 2: header value
#==============================================================================
header() {
    echo "$1: $2" >> "$SERVIES_FILE_HEADERS"
}

#=== FUNCTION =================================================================
#        NAME: not_found
# DESCRIPTION: default not found handler. overwrite for custom output
#==============================================================================
not_found() {
    status 404
    echo 404, Not found
}

#=== FUNCTION =================================================================
#        NAME: get
# DESCRIPTION: add a get route handler
# PARAMETER 1: url string (include first forward slash)
# PARAMETER 2: command name
#==============================================================================
get() {
    servies:save_route GET "$@"
}

#=== FUNCTION =================================================================
#        NAME: post
# DESCRIPTION: add a post route handler
# PARAMETER 1: url string (include first forward slash)
# PARAMETER 2: command name
#==============================================================================
post() {
    servies:save_route POST "$@"
}

#=== FUNCTION =================================================================
#        NAME: put
# DESCRIPTION: add a put route handler
# PARAMETER 1: url string (include first forward slash)
# PARAMETER 2: command name
#==============================================================================
put() {
    servies:save_route PUT "$@"
}

#=== FUNCTION =================================================================
#        NAME: patch
# DESCRIPTION: add a patch route handler
# PARAMETER 1: url string (include first forward slash)
# PARAMETER 2: command name
#==============================================================================
patch() {
    servies:save_route PATCH "$@"
}

# running as command?
if [ ! -z "$1" ]; then
    source "$1"
    servies:start
fi
